# TTC Station Reliability

Which stations are unreliable, and which just look bad because they are busy?
Delay incidents divided by scheduled trips, per station and line.

Run top to bottom. Tables persist in `ttc.duckdb`. See README for method and caveats.

## Setup — file inventory

24 files across `delay/`, `ridership/` and `schedules/`.

In [151]:
# Verifying data path

import os
import glob
import pandas as pd

paths = glob.glob("data/raw/**/*", recursive=True)

files = []
for item in paths:
    if os.path.isfile(item):
        files.append(item)

length = len(files)

print(files)
print(f"\n total files: {length}")

['data/raw\\delay\\TTC Subway Delay Data since 2025.csv', 'data/raw\\delay\\ttc-subway-delay-data-2018.xlsx', 'data/raw\\delay\\ttc-subway-delay-data-2019.xlsx', 'data/raw\\delay\\ttc-subway-delay-data-2020.xlsx', 'data/raw\\delay\\ttc-subway-delay-data-2021.xlsx', 'data/raw\\delay\\ttc-subway-delay-data-2022.xlsx', 'data/raw\\delay\\ttc-subway-delay-data-2023.xlsx', 'data/raw\\delay\\ttc-subway-delay-data-2024.xlsx', 'data/raw\\delay\\ttc-subway-delay-jan-2014-april-2017.xlsx', 'data/raw\\delay\\ttc-subway-delay-may-december-2017.xlsx', 'data/raw\\ridership\\1985-2019 Analysis of ridership.xlsx', 'data/raw\\ridership\\ttc-subway-station-usage-2012-2013.xlsx', 'data/raw\\ridership\\ttc-subway-station-usage-2014.xlsx', 'data/raw\\ridership\\ttc-subway-station-usage-2015.xlsx', 'data/raw\\ridership\\ttc-subway-station-usage-2016.xlsx', 'data/raw\\ridership\\ttc-subway-station-usage-2017.xlsx', 'data/raw\\schedules\\agency.txt', 'data/raw\\schedules\\calendar.txt', 'data/raw\\schedules\\calendar_dates.txt', 'data/raw\\schedules\\routes.txt', 'data/raw\\schedules\\shapes.txt', 'data/raw\\schedules\\stops.txt', 'data/raw\\schedules\\stop_times.txt', 'data/raw\\schedules\\trips.txt']

 total files: 24

## Load GTFS

Load `routes`. `route_type = 1` is subway: lines 1, 2 and 4.

In [152]:
# Verifying routes 

import duckdb

con = duckdb.connect("ttc.duckdb")


con.sql("CREATE OR REPLACE TABLE routes AS SELECT * " \
"FROM read_csv_auto('data/raw/schedules/routes.txt')")


con.sql("SELECT COUNT(route_id) FROM routes GROUP BY route_type").df()

   count(route_id)
0               20
1                3
2              210

In [153]:
con.sql("SELECT route_id, route_short_name, route_long_name " \
"  FROM routes " \
"WHERE route_type = 1").df()

   route_id  route_short_name            route_long_name
0         1                 1  Line 1 (Yonge-University)
1         2                 2  Line 2 (Bloor - Danforth)
2         4                 4          Line 4 (Sheppard)

### Load the remaining GTFS tables

`stops`, `stop_times`, `trips`. `stop_times` bridges trip to stop.

In [154]:
con.sql("CREATE OR REPLACE TABLE stops AS SELECT * " \
"FROM read_csv_auto('data/raw/schedules/stops.txt')")

con.sql("CREATE OR REPLACE TABLE stop_times AS SELECT * " \
"FROM read_csv_auto('data/raw/schedules/stop_times.txt')")

con.sql("CREATE OR REPLACE TABLE trips AS SELECT * " \
"FROM read_csv_auto('data/raw/schedules/trips.txt')")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

## Denominator — scheduled trips per station

Filter `stop_times` to subway trips, carrying `route_id` through. 4.2M rows to ~150k.

In [155]:
# filter in only stop time data related to subway lines

con.sql("""
    CREATE OR REPLACE TABLE subway_stop_times AS
    SELECT stop_times.*, route_id FROM trips
    JOIN stop_times 
        ON trips.trip_id = stop_times.trip_id
    WHERE trips.route_id IN [1,2,4]
""")

con.sql("""
    SELECT * FROM subway_stop_times LIMIT 5
""").df()

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,stop_headsign,pickup_type,drop_off_type,shape_dist_traveled,route_id
0,50659966,5:45:18,5:45:18,14945,1,None,0,0,NaN,1
1,50659966,5:47:44,5:47:44,15664,2,None,0,0,1.4442,1
2,50659966,5:50:22,5:50:22,15659,3,None,0,0,3.3901,1
3,50659966,5:52:34,5:52:34,15666,4,None,0,0,4.7396,1
4,50659966,5:54:26,5:54:26,15656,5,None,0,0,5.5524,1

### `parent_station` is null for TTC, so stations group on `stop_name`

In [156]:
con.sql("""
    SELECT * FROM stops LIMIT 5
""").df()

,stop_id,stop_code,stop_name,stop_desc,stop_lat,stop_lon,zone_id,stop_url,location_type,parent_station,stop_timezone,wheelchair_boarding
0,662,662,Danforth Rd at Kennedy Rd,None,43.714379,-79.260939,None,None,None,None,None,1
1,929,929,Davenport Rd at Bedford Rd,None,43.674448,-79.399659,None,None,None,None,None,1
2,940,940,Davenport Rd at Dupont St,None,43.675511,-79.401938,None,None,None,None,None,2
3,1871,1871,Davisville Ave at Cleveland St,None,43.702088,-79.378112,None,None,None,None,None,1
4,11700,11700,Disco Rd at Attwell Dr,None,43.701362,-79.594843,None,None,None,None,None,1

In [157]:
pd.set_option('display.max_rows', 20)

con.sql("""
    SELECT DISTINCT(route_type) FROM routes
""").df()

   route_type
0           3
1           1
2           0

### Station table — merge Bloor-Yonge, add geography

Bloor-Yonge is two GTFS stations: "Bloor" on Line 1, "Yonge" on Line 2. Merged here.
70 stations, 74 station-line rows. Interchanges carry both lines (Bloor-Yonge 4,332
trips, St George 4,326, Spadina 4,321, Sheppard-Yonge 3,976); others ~2,100, Line 4 ~1,760.

In [158]:
## fixing name duplicate i.e Bloor-Yonge

pd.set_option('display.max_rows', 80)

con.sql("""
    CREATE OR REPLACE TABLE station_trips AS
        SELECT 
            route_id AS line,
            SPLIT_PART(stop_name, ' -', 1) AS stations, 
            COUNT(*) AS scheduled_trips,
            AVG(stop_lat) AS lat,
            AVG(stop_lon) AS lon
        FROM stops
        JOIN subway_stop_times
            ON subway_stop_times.stop_id = stops.stop_id
        GROUP BY stations, line
        ORDER BY stations ASC
""")

con.sql("""
    CREATE OR REPLACE TABLE station_geo AS
        WITH 
        s1 AS (
            SELECT * REPLACE (SPLIT_PART(stations, ' Station' , 1) AS stations) FROM station_trips),
        s2 AS (
            SELECT * REPLACE (UPPER(stations) AS stations) FROM s1),
        s3 AS (
            SELECT * RENAME (stations AS station) FROM s2),
        s4 AS (
            SELECT * REPLACE (
                CASE WHEN station IN ('BLOOR', 'YONGE') THEN 'BLOOR-YONGE'
                ELSE station END AS station)
            FROM s3)
    SELECT * FROM s4
""")

con.sql("""
    CREATE OR REPLACE TABLE station_trips_clean AS
        SELECT * EXCLUDE(lat, lon) FROM station_geo
""")


con.sql("""SELECT * FROM station_geo""").df()

    line                      station  scheduled_trips        lat        lon
0      2                     BATHURST             2137  43.665798 -79.411443
1      2                          BAY             2136  43.669998 -79.390942
2      4                      BAYVIEW             1755  43.766912 -79.386717
3      4                    BESSARION             1758  43.769249 -79.376329
4      1                  BLOOR-YONGE             2196  43.670546 -79.385654
5      2                    BROADVIEW             2133  43.676698 -79.358840
6      2                 CASTLE FRANK             2133  43.673798 -79.368940
7      1                    CEDARVALE             2181  43.700002 -79.436492
8      2                      CHESTER             2133  43.678296 -79.352520
9      2                     CHRISTIE             2139  43.664298 -79.418144
10     1                      COLLEGE             2195  43.660799 -79.382888
11     2                      COXWELL             2158  43.684404 -79.322808
12     1                   DAVISVILLE             2190  43.697650 -79.397091
13     4                    DON MILLS             1761  43.775397 -79.346386
14     2                     DONLANDS             2133  43.681049 -79.338339
15     1               DOWNSVIEW PARK             2154  43.753311 -79.478693
16     2                     DUFFERIN             2139  43.660698 -79.434795
17     2                  DUNDAS WEST             2139  43.657298 -79.451945
18     1                       DUPONT             2184  43.674352 -79.406891
19     1                     EGLINTON             2223  43.705615 -79.398636
20     1                        FINCH             2224  43.780503 -79.415488
21     1                   FINCH WEST             2154  43.764855 -79.491118
22     1                    GLENCAIRN             2181  43.708602 -79.440544
23     2                    GREENWOOD             2158  43.682694 -79.330865
24     2                    HIGH PARK             2155  43.653697 -79.467852
25     1                  HIGHWAY 407             2154  43.783359 -79.523454
26     2                    ISLINGTON             2155  43.645396 -79.524154
27     2                         JANE             2155  43.649946 -79.483753
28     2                        KEELE             2155  43.655497 -79.459552
29     2                      KENNEDY             2158  43.732324 -79.264234
30     1                         KING             2195  43.649049 -79.377888
31     2                      KIPLING             2155  43.637518 -79.535794
32     2                    LANSDOWNE             2139  43.659280 -79.442467
33     1                     LAWRENCE             2223  43.725959 -79.402392
34     1                LAWRENCE WEST             2181  43.715270 -79.443915
35     4                       LESLIE             1761  43.771298 -79.365892
36     2                  MAIN STREET             2158  43.689104 -79.301508
37     1                       MUSEUM             2189  43.666601 -79.393190
38     1            NORTH YORK CENTRE             2224  43.767958 -79.412543
39     2                     OLD MILL             2155  43.649752 -79.494151
40     1                      OSGOODE             2191  43.651100 -79.386688
41     2                    OSSINGTON             2139  43.662198 -79.426995
42     2                         PAPE             2133  43.679799 -79.344939
43     1              PIONEER VILLAGE             2154  43.776745 -79.509352
44     1                        QUEEN             2195  43.652749 -79.379388
45     1                 QUEEN'S PARK             2189  43.659901 -79.390490
46     1                     ROSEDALE             2196  43.676649 -79.388339
47     2                   ROYAL YORK             2155  43.648447 -79.509604
48     2                    RUNNYMEDE             2155  43.651897 -79.475853
49     1                SHEPPARD WEST             2154  43.749702 -79.462407
50     1               SHEPPARD-YONGE             2224  43.761010 -79.410793
51     4               SHEPPARD-YONGE             1752  43.761572 -79.410241
52     2                   SHERBOURNE             2133  43.672139 -79.376168
53     2                      SPADINA             2137  43.667098 -79.404793
54     1                      SPADINA             2184  43.669652 -79.404990
55     1                    ST ANDREW             2191  43.647650 -79.384789
56     1                     ST CLAIR             2196  43.688049 -79.393289
57     1                ST CLAIR WEST             2184  43.684551 -79.415641
58     2                    ST GEORGE             2137  43.668398 -79.398843
59     1                    ST GEORGE             2189  43.668399 -79.398792
60     1                   ST PATRICK             2191  43.654650 -79.388188
61     1                   SUMMERHILL             2196  43.682699 -79.390989
62     1                          TMU             2195  43.656549 -79.380988
63     1                        UNION             2195  43.645699 -79.380588
64     1  VAUGHAN METROPOLITAN CENTRE             2154  43.794021 -79.527906
65     2                VICTORIA PARK             2158  43.694907 -79.288658
66     2                       WARDEN             2158  43.711569 -79.278930
67     1                    WELLESLEY             2195  43.665549 -79.383638
68     1                       WILSON             2181  43.734452 -79.450043
69     2                     WOODBINE             2158  43.686504 -79.313108
70     2                  BLOOR-YONGE             2136  43.671023 -79.386374
71     1                   YORK MILLS             2224  43.743859 -79.406093
72     1              YORK UNIVERSITY             2154  43.774097 -79.499888
73     1                     YORKDALE             2181  43.724602 -79.447493

In [159]:
pd.set_option('display.max_rows', 20)

con.sql("""
CREATE OR REPLACE TABLE station_lines AS
    SELECT station,
           COUNT(*) AS n_lines,
           ANY_VALUE(line) AS sole_line
    FROM station_trips_clean
    GROUP BY station
""")

con.sql("""
    SELECT * FROM station_lines
""").df()

            station  n_lines  sole_line
0          BATHURST        1          2
1          ST CLAIR        1          1
2               TMU        1          1
3         BESSARION        1          4
4        ROYAL YORK        1          2
5       BLOOR-YONGE        2          1
6      CASTLE FRANK        1          2
7          WOODBINE        1          2
8           BAYVIEW        1          4
9       DUNDAS WEST        1          2
..              ...      ...        ...
60        LANSDOWNE        1          2
61         LAWRENCE        1          1
62  YORK UNIVERSITY        1          1
63         YORKDALE        1          1
64         DONLANDS        1          2
65          KENNEDY        1          2
66             KING        1          1
67             PAPE        1          2
68    SHEPPARD WEST        1          1
69   SHEPPARD-YONGE        2          1

[70 rows x 3 columns]

## Load delay data

10 files, Jan 2014 – Jun 2026 — but **61 sheets**. Five workbooks are one sheet per
month, so `sheet_name=None` is required; the default drops 76k rows silently.

In [160]:
## Verifying delay datas

paths = glob.glob("data/raw/delay/**")

for f in paths:
    if os.path.splitext(f)[1].lower() == '.xlsx':
        df = pd.read_excel(f, nrows=0)
    else:
        df = pd.read_csv(f, nrows=0)
    print(f, df.columns.tolist())

path = "data/raw/delay/ttc-subway-delay-jan-2014-april-2017.xlsx"
sheets = pd.read_excel(path, sheet_name=None)
print(sheets.keys())

print(sheets['Incidents']['Date'].min())
print(sheets['Incidents']['Date'].max())

data/raw/delay\TTC Subway Delay Data since 2025.csv ['_id', 'Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
data/raw/delay\ttc-subway-delay-data-2018.xlsx ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
data/raw/delay\ttc-subway-delay-data-2019.xlsx ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
data/raw/delay\ttc-subway-delay-data-2020.xlsx ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
data/raw/delay\ttc-subway-delay-data-2021.xlsx ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
data/raw/delay\ttc-subway-delay-data-2022.xlsx ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
data/raw/delay\ttc-subway-delay-data-2023.xlsx ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
data/raw/delay\ttc-subway-delay-data-2024.xlsx ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
data/raw/delay\ttc-subway-delay-jan-2014-april-2017.xlsx ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
data/raw/delay\ttc-subway-delay-may-december-2017.xlsx ['Date', 'Time', 'Day', 'Station', 'Code', 'Min Delay', 'Min Gap', 'Bound', 'Line', 'Vehicle']
dict_keys(['Incidents'])
2014-01-01 00:00:00
2017-04-30 00:00:00

In [161]:
paths = glob.glob("data/raw/delay/**")

dfs = []

for f in paths:
    if os.path.splitext(f)[1].lower() == '.xlsx':
        dfs.extend(pd.read_excel(f, sheet_name=None).values())
    else:
        dfs.append(pd.read_csv(f))

all_delays = pd.concat(dfs, ignore_index=True)

## all_delays.shape

(all_delays.dtypes.to_string())

## print(all_delays['Date'].max())
## print(all_delays['Date'].min())

'_id          float64\nDate          object\nTime             str\nDay              str\nStation          str\nCode             str\nMin Delay      int64\nMin Gap        int64\nBound            str\nLine             str\nVehicle        int64'

### Station name concentration

2,178 distinct station values against a true 70. Top 70 cover ~90% of rows, top 150 ~98%.

In [162]:
pd.set_option('display.max_rows', 100)

con.sql("""
CREATE OR REPLACE TABLE raw_delays AS
SELECT * FROM all_delays 
""")

n = con.sql("SELECT COUNT(DISTINCT Station) AS n FROM raw_delays").fetchone()[0]

print(f"distinct stations: {n}\n")

con.sql("""
WITH ranked AS (
    SELECT
        Station, 
        COUNT(Station) AS count,
        count / SUM(COUNT(*)) OVER () AS ratio,
        SUM(COUNT(*)) OVER (ORDER BY COUNT(*) DESC) as r_total,
        r_total / SUM(COUNT(*)) OVER () AS r_ratio,
        ROW_NUMBER() OVER (ORDER BY COUNT(*) DESC) AS r_num
    FROM raw_delays
    GROUP BY Station
    ORDER BY Count DESC
)
SELECT * FROM ranked WHERE r_num IN (74,150)
""").df()

distinct stations: 2178

                 Station  count     ratio   r_total   r_ratio  r_num
0     FINCH WEST STATION   1256  0.004775  241797.0  0.919300     74
1  BLOOR DANFORTH LINE 2     24  0.000091  258660.0  0.983412    150

### Raw delay table

263,023 rows, before cleaning.

In [163]:
con.sql("""
SELECT * FROM all_delays
""").df()

,_id,Date,Time,Day,Station,Code,Min Delay,Min Gap,Bound,Line,Vehicle
0,1.0,2025-01-01,02:10,Wednesday,BATHURST STATION,MUSAN,5,9,E,BD,5227
1,2.0,2025-01-01,02:30,Wednesday,DUNDAS STATION,MUIRS,0,0,NaN,YU,0
2,3.0,2025-01-01,02:32,Wednesday,BROADVIEW STATION,PUMST,0,0,E,BD,0
3,4.0,2025-01-01,02:58,Wednesday,KEELE STATION,EUSC,0,0,W,BD,5293
4,5.0,2025-01-01,02:58,Wednesday,COXWELL STATION,SUAE,0,0,NaN,BD,0
5,6.0,2025-01-01,07:59,Wednesday,DONLANDS STATION,TUNOA,5,10,W,BD,5000
6,7.0,2025-01-01,08:13,Wednesday,BLOOR STATION,PUTR,9,0,S,YU,5836
7,8.0,2025-01-01,08:15,Wednesday,BLOOR STATION,PUTR,5,0,N,YU,5706
8,9.0,2025-01-01,09:14,Wednesday,FINCH STATION,SUDP,0,0,S,YU,5596
9,10.0,2025-01-01,09:22,Wednesday,BATHURST STATION,SUUT,0,0,E,BD,5312
10,11.0,2025-01-01,09:58,Wednesday,WILSON STATION,MUIS,0,0,NaN,YU,0
11,12.0,2025-01-01,10:08,Wednesday,KENNEDY BD STATION,TUSC,0,0,E,BD,5253
12,13.0,2025-01-01,12:56,Wednesday,VAUGHAN MC STATION,MUO,4,8,S,YU,5706
13,14.0,2025-01-01,13:11,Wednesday,ST GEORGE BD STATION,SUUT,0,0,E,BD,5253
14,15.0,2025-01-01,13:34,Wednesday,OSGOODE STATION,SUUT,0,0,N,YU,0
15,16.0,2025-01-01,13:44,Wednesday,COLLEGE STATION,MUPAA,3,7,N,YU,5606
16,17.0,2025-01-01,14:09,Wednesday,QUEEN'S PARK STATION,MUPAA,0,0,S,YU,5736
17,18.0,2025-01-01,14:46,Wednesday,WELLESLEY STATION,SUAE,0,0,S,YU,5701
18,19.0,2025-01-01,14:56,Wednesday,ST PATRICK STATION,MUPAA,5,9,N,YU,5601
19,20.0,2025-01-01,15:07,Wednesday,FINCH STATION,MUPLC,0,0,NaN,YU,0
...,...,...,...,...,...,...,...,...,...,...,...
263003,NaN,2017-12-31 00:00:00,19:19,Sunday,YONGE SHP STATION,TUSC,0,0,W,SHP,6191
263004,NaN,2017-12-31 00:00:00,19:27,Sunday,SHEPPARD WEST STATION,TUATC,12,16,N,YU,6106
263005,NaN,2017-12-31 00:00:00,20:12,Sunday,GREENWOOD WYE,EUOE,10,14,E,BD,5361
263006,NaN,2017-12-31 00:00:00,20:14,Sunday,SHERBOURNE STATION,SUAP,0,0,NaN,BD,0
263007,NaN,2017-12-31 00:00:00,20:29,Sunday,KIPLING STATION,MUPAA,0,0,W,BD,5064
263008,NaN,2017-12-31 00:00:00,20:46,Sunday,DAVISVILLE STATION,SUDP,9,14,N,YU,5446
263009,NaN,2017-12-31 00:00:00,20:47,Sunday,KENNEDY BD STATION,MUSC,6,10,W,BD,5238
263010,NaN,2017-12-31 00:00:00,21:16,Sunday,ST CLAIR STATION,MUSC,0,0,S,YU,5401
263011,NaN,2017-12-31 00:00:00,21:33,Sunday,QUEEN STATION,SUUT,5,9,N,YU,5736
263012,NaN,2017-12-31 00:00:00,21:52,Sunday,YORK MILLS STATION,SUDP,3,8,N,YU,5851
263013,NaN,2017-12-31 00:00:00,22:00,Sunday,YUS/BD/SHEPPARD SUBWAY,MUO,0,0,NaN,YU/BD,0
263014,NaN,2017-12-31 00:00:00,22:43,Sunday,KIPLING STATION,MUIS,0,0,E,BD,0
263015,NaN,2017-12-31 00:00:00,22:46,Sunday,BROADVIEW STATION,SUDP,4,8,E,BD,5261
263016,NaN,2017-12-31 00:00:00,23:06,Sunday,WARDEN STATION,EUDO,4,8,E,BD,5330
263017,NaN,2017-12-31 00:00:00,23:11,Sunday,WELLESLEY STATION,MUPAA,0,0,S,YU,5671
263018,NaN,2017-12-31 00:00:00,23:24,Sunday,KEELE STATION,SUUT,0,0,W,BD,5245
263019,NaN,2017-12-31 00:00:00,23:44,Sunday,BAY STATION,PUMEL,0,0,NaN,BD,0
263020,NaN,2017-12-31 00:00:00,23:44,Sunday,WARDEN STATION,MUSC,0,0,W,BD,5225
263021,NaN,2017-12-31 00:00:00,23:58,Sunday,GLENCAIRN STATION,SUUT,10,14,S,YU,5576
263022,NaN,2017-12-31 00:00:00,23:59,Sunday,LAWRENCE STATION,SUUT,0,0,N,YU,6136

## Clean layer

One rule per CTE; order matters.

- **s1** drops Line 3 (SRT), 7,672 rows — before the suffix strip, or Kennedy SRT merges into Kennedy
- **s1a** drops two-station segments and surface routes, 1,282 rows — before `s2` destroys the ` TO ` marker
- **s2–s18** normalise station names
- **s19** drops shuttle records, 826 rows
- **s21** maps `Line` to numeric `route`; **s22** rebuilds the timestamp

`clean_delays_all` = 253,243 rows. `clean_delays_1` then joins on (station, route).

In [164]:
pd.set_option('display.max_rows', 25)

con.sql(r"""
CREATE OR REPLACE TABLE clean_delays_all AS 
    WITH 
    s1 AS (
        SELECT * FROM raw_delays WHERE Line IS DISTINCT FROM 'SRT'),
    s1a AS (
        SELECT * FROM s1 WHERE NOT station LIKE '% TO %' AND (Line IS NULL OR Line NOT SIMILAR TO '\d.*')),
    s2 AS (
        SELECT * REPLACE (SPLIT_PART(Station, ' STATION', 1) AS Station) FROM s1a),
    s3 AS (
        SELECT * REPLACE (REGEXP_REPLACE(Station, ' (BD|YU|YUS|SRT)$', '') AS Station) FROM s2),
    s4 AS (
        SELECT * REPLACE (REGEXP_REPLACE(Station, 'SHEPPARDSTATION$', 'SHEPPARD-YONGE') AS Station) FROM s3),
    s5 AS (
        SELECT * REPLACE (REGEXP_REPLACE(Station, 'BLOOR YONGE', 'BLOOR-YONGE') AS Station) FROM s4),
    s6 AS (
        SELECT * RENAME (Station AS station) FROM s5),
    s7 AS (
        SELECT * REPLACE (REPLACE(station, '.', '') AS station) FROM s6),
    s8 AS (
        SELECT * REPLACE (REPLACE(station, 'EGLINTON WEST', 'CEDARVALE') AS station) FROM s7),
    s9 AS (
        SELECT * REPLACE (REGEXP_REPLACE(station, '^DUNDAS$', 'TMU') AS station) FROM s8),
    s11 AS (
        SELECT * REPLACE (REGEXP_REPLACE(station, '^BLOOR$', 'BLOOR-YONGE') AS station) FROM s9),
    s12 AS (
        SELECT * REPLACE (REGEXP_REPLACE(station, '^YONGE$', 'BLOOR-YONGE') AS station) FROM s11),
    s13 AS (
        SELECT * REPLACE (REGEXP_REPLACE(station, '^SHEPPARD$', 'SHEPPARD-YONGE') AS station) FROM s12),
    s14 AS (
        SELECT * REPLACE (REGEXP_REPLACE(station, '^VAUGHAN MC$', 'VAUGHAN METROPOLITAN CENTRE') AS station) FROM s13),
    s15 AS (
        SELECT * REPLACE (REPLACE(station, 'CTR', 'CENTRE') AS station) FROM s14),
    s16 AS (
        SELECT * REPLACE (REPLACE(station, 'VMC', 'VAUGHAN METROPOLITAN CENTRE') AS station) FROM s15),
    s17 AS (
        SELECT * REPLACE (REPLACE(station, 'YONGE SHP', 'SHEPPARD-YONGE') AS station) FROM s16),
    s18 AS (
        SELECT * REPLACE (REGEXP_REPLACE(station, ' STATIO$', '') AS station) FROM s17),
    s19 AS (
        SELECT * EXCLUDE(Date), SPLIT_PART(Date, ' ', 1) AS Date_normalized FROM s18),
    s20 AS (
        SELECT * FROM s19 WHERE Line NOT LIKE '%SHUTTLE%'),
    s21 AS (
        SELECT *, 
                CASE Line 
                    WHEN 'YUS' THEN 1
                    WHEN 'YU' THEN 1
                    WHEN 'BD' THEN 2
                    WHEN 'SHP' THEN 4
                    WHEN 'SHEP' THEN 4
                END AS route
            FROM s20),
    s22 AS (
        SELECT * EXCLUDE(_id, Time, Date_normalized), STRPTIME(Date_normalized || ' ' || Time, '%Y-%m-%d %H:%M') AS Timestamp FROM s21)
SELECT * FROM s22
""")

con.sql("""
    CREATE OR REPLACE TABLE clean_delays_1 AS 
        SELECT * EXCLUDE(t2.station, scheduled_trips, Line) FROM clean_delays_all t1
        LEFT JOIN station_trips_clean t2
            ON t1.station = t2.station AND t1.route = t2.line
        WHERE t2.station IS NOT NULL
""")

result = con.sql("""
    SELECT * FROM clean_delays_1
""").df()

result

,Day,station,Code,Min Delay,Min Gap,Bound,Vehicle,route,Timestamp
0,Thursday,QUEEN'S PARK,MUI,8,11,S,5961,1,2017-08-10 09:07:00
1,Thursday,MUSEUM,MUIR,4,7,S,5491,1,2017-08-10 09:18:00
2,Thursday,MUSEUM,MUIR,14,17,S,5551,1,2017-08-10 09:20:00
3,Thursday,ST CLAIR WEST,MUIR,0,0,S,5951,1,2017-08-10 09:32:00
4,Thursday,BLOOR-YONGE,MUPAA,0,0,S,5996,1,2017-08-10 09:39:00
5,Thursday,COLLEGE,MUI,7,10,S,5516,1,2017-08-10 09:42:00
6,Thursday,BLOOR-YONGE,SUSP,0,0,NaN,0,1,2017-08-10 09:48:00
7,Thursday,BLOOR-YONGE,MUIR,6,9,N,5711,1,2017-08-10 09:55:00
8,Thursday,KIPLING,MUIS,0,0,NaN,0,2,2017-08-10 10:07:00
9,Thursday,LESLIE,TUSC,0,0,W,6176,4,2017-08-10 10:28:00
10,Thursday,WILSON,MUSC,0,0,S,5821,1,2017-08-10 10:35:00
11,Thursday,ROSEDALE,SUUT,14,17,N,6071,1,2017-08-10 11:37:00
...,...,...,...,...,...,...,...,...,...
237397,Thursday,SPADINA,PUTIJ,5,8,N,5956,1,2017-08-10 07:59:00
237398,Thursday,HIGH PARK,MUTO,3,5,W,5038,2,2017-08-10 08:05:00
237399,Thursday,KIPLING,PUTNT,30,32,W,5059,2,2017-08-10 08:12:00
237400,Thursday,KING,MUIR,0,0,S,5781,1,2017-08-10 08:18:00
237401,Thursday,ST ANDREW,EUTL,3,6,S,5924,1,2017-08-10 08:18:00
237402,Thursday,TMU,MUPAA,0,0,S,5626,1,2017-08-10 08:23:00
237403,Thursday,BLOOR-YONGE,MUIR,18,21,S,5391,1,2017-08-10 08:44:00
237404,Thursday,EGLINTON,MUPAA,3,6,S,6011,1,2017-08-10 08:45:00
237405,Thursday,ST CLAIR WEST,MUIS,0,0,NaN,0,1,2017-08-10 08:46:00
237406,Thursday,EGLINTON,MUIR,13,16,S,6076,1,2017-08-10 08:49:00
237407,Thursday,ROSEDALE,MUPAA,0,0,S,5791,1,2017-08-10 08:52:00
237408,Thursday,BLOOR-YONGE,MUPAA,3,5,S,6006,1,2017-08-10 09:07:00

### Inconsistent station line

Rows tagging a line that does not serve the station — TTC data entry errors.

In [165]:
pd.set_option('display.max_rows', 25)

con.sql("""
    WITH table1 AS (
        SELECT * EXCLUDE (t2.station) FROM clean_delays_all t1
        JOIN ( SELECT DISTINCT station FROM station_trips_clean) t2
            ON t1.station = t2.station
        WHERE t2.station IS NOT NULL
    )

    SELECT t1.station, route, COUNT(t1.station) AS count FROM table1 t1
    LEFT JOIN station_trips_clean t2
        ON t1.route = t2.Line AND t1.station = t2.station
    WHERE t2.Line IS NULL
    GROUP BY t1.station, route
    ORDER BY count DESC
""").df()

               station  route  count
0               WARDEN      1    120
1               WARDEN   <NA>     31
2              KENNEDY      1     28
3              KIPLING      1     22
4           SHERBOURNE      1     13
5                  TMU      2     12
6                  BAY      1     11
7           ROYAL YORK      1     11
8                FINCH      2     11
9          MAIN STREET      1     10
10            DONLANDS      1     10
11            LAWRENCE      2      9
..                 ...    ...    ...
110       CASTLE FRANK   <NA>      1
111          BROADVIEW      4      1
112                TMU      4      1
113           BATHURST      4      1
114         ST PATRICK      4      1
115          CEDARVALE      2      1
116          HIGH PARK   <NA>      1
117          BESSARION      1      1
118          ST GEORGE   <NA>      1
119           DONLANDS   <NA>      1
120          WELLESLEY      4      1
121  NORTH YORK CENTRE      4      1

[122 rows x 3 columns]

### Repair table

Single-line stations: the line is implied, so take it from the station. Interchanges keep
the tagged line. 626 rows recovered, unioned onto `clean_delays_1`.

In [166]:
con.sql("""
    CREATE OR REPLACE TABLE route_repair AS (
        WITH table1 AS (
            SELECT * EXCLUDE (t2.station) FROM clean_delays_all t1
            JOIN ( SELECT DISTINCT station FROM station_trips_clean) t2
                ON t1.station = t2.station
            WHERE t2.station IS NOT NULL
        )

        SELECT t1.* EXCLUDE(Line) REPLACE (t3.sole_line AS route)
        FROM table1 t1
        LEFT JOIN station_trips_clean t2
            ON t1.route = t2.Line AND t1.station = t2.station
        LEFT JOIN station_lines t3
            ON t1.station = t3.station
        WHERE t2.Line IS NULL AND n_lines = 1
    )
""")

con.sql("""
    SELECT * FROM route_repair
""").df()

,Day,station,Code,Min Delay,Min Gap,Bound,Vehicle,route,Timestamp
0,Monday,CASTLE FRANK,MUIS,0,0,NaN,7776,2,2017-10-09 17:18:00
1,Thursday,GLENCAIRN,MUSC,0,0,W,5288,1,2017-10-12 14:34:00
2,Wednesday,VICTORIA PARK,MUSC,0,0,W,5240,2,2017-11-01 00:52:00
3,Wednesday,DONLANDS,PUSSW,0,0,W,5254,2,2017-11-01 06:23:00
4,Wednesday,PAPE,MUSC,0,0,W,5190,2,2017-11-01 07:25:00
5,Wednesday,BROADVIEW,SUAE,0,0,NaN,0,2,2017-11-01 08:32:00
6,Wednesday,VICTORIA PARK,SUDP,0,0,W,5068,2,2017-11-01 10:33:00
7,Wednesday,OLD MILL,MUO,0,0,W,5322,2,2017-11-01 11:55:00
8,Wednesday,HIGH PARK,MUIS,0,0,NaN,0,2,2017-11-01 15:03:00
9,Wednesday,VICTORIA PARK,PUTIJ,7,9,W,5312,2,2017-11-01 16:18:00
10,Thursday,KIPLING,EUSC,0,0,W,5302,2,2017-11-02 00:13:00
11,Thursday,KEELE,MUSC,0,0,W,5103,2,2017-11-02 05:41:00
...,...,...,...,...,...,...,...,...,...
614,Saturday,ST PATRICK,SUDP,6,10,N,5621,1,2016-03-12 19:29:00
615,Saturday,KENNEDY,MUIS,0,0,NaN,0,2,2016-03-12 19:52:00
616,Saturday,YORKDALE,SUSA,15,19,N,5441,1,2016-03-12 20:33:00
617,Saturday,CHRISTIE,MUSAN,4,8,W,5317,2,2016-03-12 21:17:00
618,Saturday,MUSEUM,MUSC,3,7,S,6041,1,2016-03-12 21:29:00
619,Sunday,LESLIE,MUIS,0,0,NaN,0,4,2016-03-27 10:01:00
620,Saturday,LAWRENCE,SUEAS,7,11,S,5966,1,2016-04-16 22:18:00
621,Thursday,ISLINGTON,TUSC,0,0,W,5042,2,2016-07-14 12:00:00
622,Tuesday,JANE,TUSC,0,0,W,6081,2,2016-07-26 18:43:00
623,Tuesday,BROADVIEW,SUEAS,8,10,W,5916,2,2016-08-02 19:07:00
624,Tuesday,WARDEN,MUSC,0,0,E,5771,2,2016-08-09 15:37:00
625,Friday,OLD MILL,TUSC,0,0,E,5324,2,2016-11-11 13:16:00

In [167]:
con.sql("""
    CREATE OR REPLACE TABLE clean_delays AS (
        SELECT * FROM clean_delays_1
        UNION ALL 
        SELECT * FROM route_repair
    )
""")

con.sql("""
    SELECT * FROM clean_delays
""").df()

,Day,station,Code,Min Delay,Min Gap,Bound,Vehicle,route,Timestamp
0,Thursday,QUEEN'S PARK,MUI,8,11,S,5961,1,2017-08-10 09:07:00
1,Thursday,MUSEUM,MUIR,4,7,S,5491,1,2017-08-10 09:18:00
2,Thursday,MUSEUM,MUIR,14,17,S,5551,1,2017-08-10 09:20:00
3,Thursday,ST CLAIR WEST,MUIR,0,0,S,5951,1,2017-08-10 09:32:00
4,Thursday,BLOOR-YONGE,MUPAA,0,0,S,5996,1,2017-08-10 09:39:00
5,Thursday,COLLEGE,MUI,7,10,S,5516,1,2017-08-10 09:42:00
6,Thursday,BLOOR-YONGE,SUSP,0,0,NaN,0,1,2017-08-10 09:48:00
7,Thursday,BLOOR-YONGE,MUIR,6,9,N,5711,1,2017-08-10 09:55:00
8,Thursday,KIPLING,MUIS,0,0,NaN,0,2,2017-08-10 10:07:00
9,Thursday,LESLIE,TUSC,0,0,W,6176,4,2017-08-10 10:28:00
10,Thursday,WILSON,MUSC,0,0,S,5821,1,2017-08-10 10:35:00
11,Thursday,ROSEDALE,SUUT,14,17,N,6071,1,2017-08-10 11:37:00
...,...,...,...,...,...,...,...,...,...
238023,Saturday,ST PATRICK,SUDP,6,10,N,5621,1,2016-03-12 19:29:00
238024,Saturday,KENNEDY,MUIS,0,0,NaN,0,2,2016-03-12 19:52:00
238025,Saturday,YORKDALE,SUSA,15,19,N,5441,1,2016-03-12 20:33:00
238026,Saturday,CHRISTIE,MUSAN,4,8,W,5317,2,2016-03-12 21:17:00
238027,Saturday,MUSEUM,MUSC,3,7,S,6041,1,2016-03-12 21:29:00
238028,Sunday,LESLIE,MUIS,0,0,NaN,0,4,2016-03-27 10:01:00
238029,Saturday,LAWRENCE,SUEAS,7,11,S,5966,1,2016-04-16 22:18:00
238030,Thursday,ISLINGTON,TUSC,0,0,W,5042,2,2016-07-14 12:00:00
238031,Tuesday,JANE,TUSC,0,0,W,6081,2,2016-07-26 18:43:00
238032,Tuesday,BROADVIEW,SUEAS,8,10,W,5916,2,2016-08-02 19:07:00
238033,Tuesday,WARDEN,MUSC,0,0,E,5771,2,2016-08-09 15:37:00
238034,Friday,OLD MILL,TUSC,0,0,E,5324,2,2016-11-11 13:16:00

### After cleaning

Name concentration against `clean_delays_all`.

In [168]:
pd.set_option('display.max_rows', 100)

con.sql("""
WITH ranked AS (
    SELECT
        Station, 
        COUNT(Station) AS count,
        count / SUM(COUNT(*)) OVER () AS ratio,
        SUM(COUNT(*)) OVER (ORDER BY COUNT(*) DESC) as r_total,
        r_total / SUM(COUNT(*)) OVER () AS r_ratio,
        ROW_NUMBER() OVER (ORDER BY COUNT(*) DESC) AS r_num
    FROM clean_delays_all
    GROUP BY Station
    ORDER BY Count DESC
)
SELECT * FROM ranked WHERE r_num IN (74,150)
""").df()

          station  count     ratio   r_total   r_ratio  r_num
0       BESSARION    695  0.002744  247941.0  0.979064     74
1  OSGOODE POCKET      8  0.000032  252211.0  0.995925    150

### Every row parsed — no null timestamps

In [169]:
con.sql("""
SELECT COUNT(*) FROM clean_delays
WHERE Timestamp IS NULL
""").df()

   count_star()
0             0

### `clean_delays` after all rules

In [170]:
pd.set_option('display.min_rows', 5)

con.sql("""
SELECT *
FROM clean_delays
""").df()

,Day,station,Code,Min Delay,Min Gap,Bound,Vehicle,route,Timestamp
0,Thursday,QUEEN'S PARK,MUI,8,11,S,5961,1,2017-08-10 09:07:00
1,Thursday,MUSEUM,MUIR,4,7,S,5491,1,2017-08-10 09:18:00
...,...,...,...,...,...,...,...,...,...
238033,Tuesday,WARDEN,MUSC,0,0,E,5771,2,2016-08-09 15:37:00
238034,Friday,OLD MILL,TUSC,0,0,E,5324,2,2016-11-11 13:16:00

## Exclusion checks

15,186 rows have no GTFS station — yards, carhouses, wyes, portals, line-level records.
22 more reach a real station but carry an unusable line. `clean_delays` = 238,035, 90.5% of raw.

In [171]:
pd.set_option('display.min_rows', 10)
pd.set_option('display.max_rows', 10)

con.sql("""
SELECT t1.station, route, COUNT(*) AS count
FROM clean_delays_all AS t1 
LEFT JOIN station_trips_clean t2 
    ON t1.station = t2.station
WHERE t2.station IS NULL
GROUP BY t1.station, route 
ORDER BY count DESC
""").df()

                    station  route  count
0     YONGE UNIVERSITY LINE      1   3210
1     BLOOR DANFORTH SUBWAY      2   2564
2    YONGE-UNIVERSITY AND B   <NA>   1907
3    YUS/BD/SHEPPARD SUBWAY   <NA>    777
4            GREENWOOD YARD      2    703
..                      ...    ...    ...
894     LINE 1 YUS / LINE 2      1      1
895  YONGE UNIVESITY AND BL      2      1
896      LAKESHORE AND YORK      1      1
897  HWY 407 & DOWNSVIEW PA      1      1
898  SUBWAY CLOSURE: WEEKEN      1      1

[899 rows x 3 columns]

### Delay rows per matched station

Coverage: all 74 station-line pairs have delay rows.

In [172]:
con.sql("""
SELECT t2.station, route, COUNT(*) AS count
FROM clean_delays AS t1 
RIGHT JOIN station_trips_clean t2 
    ON t1.station = t2.station AND t1.route = t2.line
WHERE t1.station IS NOT NULL
GROUP BY t2.station, route
ORDER BY station ASC
""").df()

            station  route  count
0          BATHURST      2   2716
1               BAY      2   1957
2           BAYVIEW      4   1178
3         BESSARION      4    695
4       BLOOR-YONGE      1   7901
..              ...    ...    ...
69           WILSON      1   5648
70         WOODBINE      2   2570
71       YORK MILLS      1   3587
72  YORK UNIVERSITY      1    652
73         YORKDALE      1   2219

[74 rows x 3 columns]

### Rows with no matching station

In [173]:
con.sql("""
SELECT COUNT(*) AS count
FROM clean_delays_all AS t1 
LEFT JOIN station_trips_clean t2 
    ON t1.station = t2.station
WHERE t2.station IS NULL
""").df()

   count
0  15186

### Zero-delay rows

64% have `Min Delay = 0` — logged, no measurable delay. Excluded from the metrics below.

In [174]:
pd.set_option('display.min_rows', 30)
pd.set_option('display.max_rows', 30)

con.sql("""
SELECT COUNT(*) FROM clean_delays 
WHERE "Min Delay" > 0
""").df()

   count_star()
0         86282

In [175]:
con.sql("""
SELECT COUNT(*) FROM clean_delays 
WHERE "Min Gap" > 0
""").df()

   count_star()
0         83609

## Analysis — full range

`delay_rate` = incidents / scheduled trips, per station-line, plus p50 and p95.

Values exceed 1.0: the numerator spans 8.5 years, the denominator one GTFS week.
Read it as a relative index, not a probability.

In [176]:
## raw unreliability number

pd.set_option('display.min_rows', 40)
pd.set_option('display.max_rows', 40)

con.sql("""
CREATE OR REPLACE TABLE station_unreliability AS 
    WITH 
    s1 AS (
        SELECT station, 
            COUNT("Min Delay") AS delays, 
            SUM("Min Delay") AS total_delay, 
            AVG("Min Delay") AS avg_delay,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "Min Delay") AS p50,
            PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY "Min Delay") AS p95,
            route
        FROM clean_delays 
        WHERE "Min Delay" > 0
        GROUP BY station, route),
    s2 AS (
        SELECT 
            t1.station, 
            delays / scheduled_trips AS delay_rate, 
            delays, total_delay, avg_delay,
            p50,
            p95,
            route
        FROM s1 t1 
        JOIN station_trips_clean t2 
            ON t1.station = t2.station AND t1.route = t2.line)
    SELECT *, 
        RANK() OVER (ORDER BY delay_rate DESC) AS adjusted_rank, 
        RANK() OVER (ORDER BY delays DESC) AS raw_rank,
        raw_rank - adjusted_rank AS delta
    FROM s2
""")

con.sql("""
    SELECT * FROM station_unreliability
""").df()

,station,delay_rate,delays,total_delay,avg_delay,p50,p95,route,adjusted_rank,raw_rank,delta
0,KENNEDY,1.773401,3827,21584.0,5.639927,4.0,13.00,2,1,1,0
1,FINCH,1.689299,3757,19609.0,5.219324,4.0,10.00,1,2,2,0
2,KIPLING,1.579582,3404,18813.0,5.526733,4.0,12.00,2,3,3,0
3,EGLINTON,1.526766,3394,21805.0,6.424573,4.0,14.00,1,4,4,0
4,VAUGHAN METROPOLITAN CENTRE,1.416899,3052,14247.0,4.668087,3.0,9.00,1,5,5,0
5,WILSON,1.262265,2753,16191.0,5.881220,4.0,14.00,1,6,6,0
6,BLOOR-YONGE,1.158015,2543,16524.0,6.497837,4.0,16.00,1,7,7,0
7,SHEPPARD WEST,1.102136,2374,16979.0,7.152064,4.0,17.00,1,8,8,0
8,DAVISVILLE,0.895434,1961,13285.0,6.774605,4.0,16.00,1,9,9,0
9,COXWELL,0.868860,1875,10607.0,5.657067,4.0,12.00,2,10,10,0
10,ST GEORGE,0.819095,1793,12370.0,6.899052,5.0,15.00,1,12,11,-1
11,WARDEN,0.824838,1780,14242.0,8.001124,5.0,22.00,2,11,12,1
12,BLOOR-YONGE,0.813202,1737,13088.0,7.534830,4.0,19.00,2,13,13,0
13,GREENWOOD,0.753475,1626,9655.0,5.937884,4.0,14.00,2,14,14,0
14,ST CLAIR WEST,0.657509,1436,10569.0,7.360028,5.0,16.00,1,15,15,0
15,ST CLAIR,0.653005,1434,10124.0,7.059972,5.0,16.00,1,18,16,-2
16,ST GEORGE,0.656060,1402,10321.0,7.361626,5.0,18.00,2,16,17,1
17,UNION,0.632802,1389,10556.0,7.599712,5.0,19.00,1,19,18,-1
18,VICTORIA PARK,0.629750,1359,12509.0,9.204562,5.0,26.00,2,20,19,-1
19,YORK MILLS,0.586781,1305,10489.0,8.037548,5.0,20.00,1,22,20,-2
...,...,...,...,...,...,...,...,...,...,...,...
54,DUFFERIN,0.315101,674,5620.0,8.338279,5.0,21.00,2,55,55,0
55,ROYAL YORK,0.311833,672,6191.0,9.212798,5.0,23.00,2,56,56,0
56,JANE,0.305800,659,6633.0,10.065250,5.0,25.00,2,57,57,0
57,ST ANDREW,0.293930,644,4611.0,7.159938,5.0,18.00,1,58,58,0
58,OLD MILL,0.293735,633,6181.0,9.764613,5.0,23.40,2,59,59,0
59,ST PATRICK,0.287540,630,4531.0,7.192063,5.0,16.55,1,60,60,0
60,QUEEN'S PARK,0.279580,612,4129.0,6.746732,4.0,17.00,1,61,61,0
61,GLENCAIRN,0.267309,583,4736.0,8.123499,5.0,18.00,1,63,62,-1
62,OSGOODE,0.261068,572,4196.0,7.335664,5.0,21.00,1,64,63,-1
63,HIGH PARK,0.260325,561,4525.0,8.065954,5.0,22.00,2,65,64,-1
64,LANSDOWNE,0.259935,556,4736.0,8.517986,5.0,22.00,2,66,65,-1
65,HIGHWAY 407,0.248839,536,3894.0,7.264925,5.0,15.00,1,68,66,-2
66,FINCH WEST,0.227484,490,3554.0,7.253061,5.0,19.00,1,69,67,-2
67,LESLIE,0.267462,471,3507.0,7.445860,5.0,17.00,4,62,68,6
68,BAYVIEW,0.259259,455,3705.0,8.142857,5.0,22.30,4,67,69,2
69,RUNNYMEDE,0.211137,455,3913.0,8.600000,5.0,20.30,2,70,69,-1
70,DOWNSVIEW PARK,0.197307,425,2900.0,6.823529,5.0,18.80,1,71,71,0
71,PIONEER VILLAGE,0.156453,337,2417.0,7.172107,5.0,17.20,1,73,72,-1
72,BESSARION,0.176337,310,2161.0,6.970968,5.0,16.00,4,72,73,1
73,YORK UNIVERSITY,0.126741,273,1819.0,6.663004,5.0,17.40,1,74,74,0

### Extreme delays

Multi-hour records. Retained — p50 and p95 are used so they do not distort the ranking.

In [177]:
con.sql("""
SELECT station, route, "Min Delay", Timestamp FROM clean_delays
WHERE "Min Delay" > 400
ORDER BY "Min Delay" DESC
""").df()

          station  route  Min Delay           Timestamp
0   SHEPPARD WEST      1        900 2025-02-16 11:03:00
1        WOODBINE      2        827 2026-01-26 05:50:00
2        EGLINTON      1        807 2025-02-16 09:18:00
3   VICTORIA PARK      2        661 2026-01-25 15:21:00
4       GLENCAIRN      1        622 2026-01-25 16:12:00
5            JANE      2        575 2016-05-19 16:35:00
6         KENNEDY      2        515 2018-10-20 17:44:00
7   ST CLAIR WEST      1        505 2026-01-26 06:00:00
8          MUSEUM      1        491 2024-03-01 06:08:00
9        OLD MILL      2        484 2026-04-07 05:46:00
10      ISLINGTON      2        481 2026-01-26 06:39:00
11        COLLEGE      1        452 2015-03-24 05:59:00
12      ST GEORGE      1        450 2020-02-13 05:30:00
13       ST CLAIR      1        446 2020-05-08 16:16:00
14        KIPLING      2        441 2026-01-25 18:32:00
15    DUNDAS WEST      2        424 2014-09-30 07:55:00

### Date range verification

In [178]:
con.sql("""
SELECT MAX(Timestamp), MIN(Timestamp) FROM clean_delays
""").df()

     max("Timestamp")    min("Timestamp")
0 2026-06-30 23:55:00 2014-01-01 00:21:00

## Analysis — 2018 onward

The Vaughan extension opened Dec 2017, so those stations carry a full denominator against
a partial window in the full-range view. This version is the primary result.

In [179]:
## with 2017 line 1 extension sensitivity consideration

pd.set_option('display.min_rows', 40)
pd.set_option('display.max_rows', 40)

con.sql("""
CREATE OR REPLACE TABLE station_unreliability_2018 AS 
    WITH 
    s1 AS (
        SELECT station, 
            COUNT("Min Delay") AS delays, 
            SUM("Min Delay") AS total_delay, 
            AVG("Min Delay") AS avg_delay,
            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "Min Delay") AS p50,
            PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY "Min Delay") AS p95,
            route
        FROM clean_delays 
        WHERE "Min Delay" > 0 AND Timestamp >= '2018-01-01'
        GROUP BY station, route),
    s2 AS (
        SELECT 
            t1.station, 
            delays / scheduled_trips AS delay_rate, 
            delays, total_delay, avg_delay,
            p50,
            p95,
            route
        FROM s1 t1 
        JOIN station_trips_clean t2 
            ON t1.station = t2.station AND t1.route = t2.line)
    SELECT *, 
        RANK() OVER (ORDER BY delay_rate DESC) AS adjusted_rank, 
        RANK() OVER (ORDER BY delays DESC) AS raw_rank,
        raw_rank - adjusted_rank AS delta
    FROM s2
""")

con.sql("""
    SELECT * FROM station_unreliability_2018
""").df()

,station,delay_rate,delays,total_delay,avg_delay,p50,p95,route,adjusted_rank,raw_rank,delta
0,VAUGHAN METROPOLITAN CENTRE,1.407614,3032,14140.0,4.663588,3.0,9.00,1,1,1,0
1,FINCH,1.314748,2924,15404.0,5.268126,4.0,11.00,1,2,2,0
2,KENNEDY,1.276182,2754,15916.0,5.779230,4.0,14.00,2,3,3,0
3,KIPLING,1.154524,2488,14643.0,5.885450,4.0,13.00,2,4,4,0
4,EGLINTON,1.107512,2462,16672.0,6.771730,5.0,15.00,1,5,5,0
5,WILSON,1.020174,2225,13220.0,5.941573,4.0,14.00,1,6,6,0
6,BLOOR-YONGE,0.877960,1928,12877.0,6.678942,4.0,17.00,1,7,7,0
7,SHEPPARD WEST,0.735376,1584,12838.0,8.104798,5.0,18.00,1,8,8,0
8,DAVISVILLE,0.674429,1477,10583.0,7.165200,5.0,17.00,1,10,9,-1
9,COXWELL,0.677943,1463,8417.0,5.753247,4.0,12.00,2,9,10,1
10,ST GEORGE,0.614436,1345,9432.0,7.012639,5.0,16.00,1,11,11,0
11,WARDEN,0.584337,1261,10599.0,8.405234,5.0,23.00,2,13,12,-1
12,BLOOR-YONGE,0.584738,1249,9780.0,7.830264,5.0,20.00,2,12,13,1
13,GREENWOOD,0.564875,1219,7569.0,6.209188,4.0,15.10,2,14,14,0
14,ST CLAIR,0.537341,1180,8507.0,7.209322,5.0,17.00,1,15,15,0
15,UNION,0.479727,1053,8264.0,7.848053,5.0,19.00,1,16,16,0
16,LAWRENCE,0.461538,1026,8748.0,8.526316,5.0,21.00,1,19,17,-2
17,ST CLAIR WEST,0.467949,1022,7748.0,7.581213,5.0,17.00,1,17,18,1
18,ROSEDALE,0.457650,1005,7817.0,7.778109,5.0,20.00,1,20,19,-1
19,KEELE,0.464037,1000,7839.0,7.839000,5.0,18.00,2,18,20,2
...,...,...,...,...,...,...,...,...,...,...,...
54,DUFFERIN,0.228612,489,3985.0,8.149284,4.0,21.00,2,55,55,0
55,WOODBINE,0.226135,488,6051.0,12.399590,5.0,28.30,2,57,56,-1
56,FINCH WEST,0.226091,487,3538.0,7.264887,5.0,19.00,1,58,57,-1
57,ST ANDREW,0.221360,485,3694.0,7.616495,5.0,19.00,1,59,58,-1
58,CHESTER,0.226910,484,3268.0,6.752066,5.0,18.00,2,56,59,3
59,ROYAL YORK,0.220882,476,4395.0,9.233193,5.0,22.25,2,60,60,0
60,OSGOODE,0.216796,475,3599.0,7.576842,5.0,22.30,1,61,61,0
61,QUEEN'S PARK,0.213796,468,3198.0,6.833333,5.0,16.00,1,63,62,-1
62,OLD MILL,0.214385,462,4597.0,9.950216,5.0,23.00,2,62,63,1
63,GLENCAIRN,0.209995,458,4026.0,8.790393,5.0,20.00,1,64,64,0
64,JANE,0.196288,423,4272.0,10.099291,5.0,26.90,2,66,65,-1
65,DOWNSVIEW PARK,0.194522,419,2863.0,6.832936,5.0,19.00,1,67,66,-1
66,HIGH PARK,0.187007,403,3394.0,8.421836,5.0,23.80,2,68,67,-1
67,LANSDOWNE,0.179991,385,3271.0,8.496104,5.0,21.80,2,70,68,-2
68,LESLIE,0.197615,348,2574.0,7.396552,5.0,17.00,4,65,69,4
69,PIONEER VILLAGE,0.155525,335,2408.0,7.188060,5.0,17.30,1,71,70,-1
70,RUNNYMEDE,0.152204,328,2910.0,8.871951,5.0,21.65,2,72,71,-1
71,BAYVIEW,0.183476,322,2641.0,8.201863,5.0,22.95,4,69,72,3
72,YORK UNIVERSITY,0.126277,272,1802.0,6.625000,5.0,17.45,1,73,73,0
73,BESSARION,0.125711,221,1566.0,7.085973,5.0,16.00,4,74,74,0

## GTFS service calendar

Loaded, not used — the denominator does not weight trips by how many days each service runs.

In [180]:
con.sql("""
CREATE OR REPLACE TABLE calendar AS
    SELECT * FROM read_csv_auto('data/raw/schedules/calendar.txt')
""")

con.sql("""
SELECT * FROM calendar
""").df()

,service_id,monday,tuesday,wednesday,thursday,friday,saturday,sunday,start_date,end_date
0,1,1,1,1,1,1,0,0,20260726,20260905
1,2,0,0,0,0,0,1,0,20260726,20260905
2,3,0,0,0,0,0,0,1,20260726,20260905
3,4,0,0,0,0,0,0,0,20260726,20260905
4,501,0,0,0,0,0,0,0,20260726,20260905
5,6701,0,0,0,0,0,0,0,20260726,20260905
6,4401,0,0,0,0,0,0,0,20260726,20260905
7,4501,0,0,0,0,0,0,0,20260726,20260905
8,7001,0,0,0,0,0,0,0,20260726,20260905
9,6702,0,0,0,0,0,0,0,20260726,20260905
10,6703,0,0,0,0,0,0,0,20260726,20260905
11,6704,0,0,0,0,0,0,0,20260726,20260905

### Sensitivity: full range vs 2018

Positive `adjusted_diff` means the station ranked better in the full-range view than it should have.

In [181]:
con.sql("""
SELECT 
    t1.station, 
    t1.raw_rank - t2.raw_rank AS raw_diff,
    t1.adjusted_rank - t2.adjusted_rank AS adjusted_diff,
    t1.route
FROM station_unreliability t1 
JOIN station_unreliability_2018 t2
    ON t1.station = t2.station AND t1.route = t2.route
ORDER BY adjusted_diff DESC
""").df()

## the more positive the worst the delay

                        station  raw_diff  adjusted_diff  route
0                   HIGHWAY 407        16             18      1
1                    FINCH WEST        10             11      1
2                    ST PATRICK         6              6      1
3                      ROSEDALE         5              6      1
4             NORTH YORK CENTRE         4              5      1
5                       SPADINA         5              5      1
6                DOWNSVIEW PARK         5              4      1
7   VAUGHAN METROPOLITAN CENTRE         4              4      1
8                      YORKDALE         6              4      1
9                      LAWRENCE         4              4      1
10                        KEELE         2              3      2
11                      OSGOODE         2              3      1
12                       MUSEUM         2              3      1
13                         KING         3              3      1
14                     ST CLAIR         1              3      1
15                        UNION         2              3      1
16                    WELLESLEY         3              3      1
17              PIONEER VILLAGE         2              2      1
18                   SUMMERHILL         3              2      1
19                       DUPONT         5              2      1
..                          ...       ...            ...    ...
54                ST CLAIR WEST        -3             -2      1
55                      BAYVIEW        -3             -2      4
56                    OSSINGTON        -3             -2      2
57                   YORK MILLS        -1             -2      1
58                      SPADINA        -4             -3      2
59                     OLD MILL        -4             -3      2
60                    CEDARVALE        -3             -3      1
61                      CHESTER        -6             -3      2
62                    DON MILLS        -7             -3      4
63                    HIGH PARK        -3             -3      2
64                    ISLINGTON        -3             -3      2
65                       LESLIE        -1             -3      4
66                     WOODBINE        -2             -3      2
67                    LANSDOWNE        -3             -4      2
68                   ROYAL YORK        -4             -4      2
69                    ST GEORGE        -6             -5      2
70                   SHERBOURNE        -4             -6      2
71                         JANE        -8             -9      2
72               SHEPPARD-YONGE        -3             -9      4
73                     CHRISTIE        -9            -10      2

[74 rows x 4 columns]

## Top 10 — adjusted rank, full range

In [182]:
con.sql("""
SELECT station, route, adjusted_rank FROM station_unreliability
ORDER BY adjusted_rank ASC
LIMIT 10
""").df()

                       station  route  adjusted_rank
0                      KENNEDY      2              1
1                        FINCH      1              2
2                      KIPLING      2              3
3                     EGLINTON      1              4
4  VAUGHAN METROPOLITAN CENTRE      1              5
5                       WILSON      1              6
6                  BLOOR-YONGE      1              7
7                SHEPPARD WEST      1              8
8                   DAVISVILLE      1              9
9                      COXWELL      2             10

## Top 10 — adjusted rank, 2018 onward

In [183]:
con.sql("""
SELECT station, route, adjusted_rank FROM station_unreliability_2018
ORDER BY adjusted_rank ASC
LIMIT 10
""").df()

                       station  route  adjusted_rank
0  VAUGHAN METROPOLITAN CENTRE      1              1
1                        FINCH      1              2
2                      KENNEDY      2              3
3                      KIPLING      2              4
4                     EGLINTON      1              5
5                       WILSON      1              6
6                  BLOOR-YONGE      1              7
7                SHEPPARD WEST      1              8
8                      COXWELL      2              9
9                   DAVISVILLE      1             10

## Top 10 — raw count, full range

In [184]:
con.sql("""
SELECT station, route, raw_rank FROM station_unreliability
ORDER BY raw_rank ASC
LIMIT 10
""").df()

                       station  route  raw_rank
0                      KENNEDY      2         1
1                        FINCH      1         2
2                      KIPLING      2         3
3                     EGLINTON      1         4
4  VAUGHAN METROPOLITAN CENTRE      1         5
5                       WILSON      1         6
6                  BLOOR-YONGE      1         7
7                SHEPPARD WEST      1         8
8                   DAVISVILLE      1         9
9                      COXWELL      2        10

## Top 10 — raw count, 2018 onward

Against the adjusted list: which stations are only bad because they are busy.

In [185]:
con.sql("""
SELECT station, route, raw_rank FROM station_unreliability_2018
ORDER BY raw_rank ASC
LIMIT 10
""").df()

                       station  route  raw_rank
0  VAUGHAN METROPOLITAN CENTRE      1         1
1                        FINCH      1         2
2                      KENNEDY      2         3
3                      KIPLING      2         4
4                     EGLINTON      1         5
5                       WILSON      1         6
6                  BLOOR-YONGE      1         7
7                SHEPPARD WEST      1         8
8                   DAVISVILLE      1         9
9                      COXWELL      2        10

### Denominator recap

In [186]:
con.sql("""
    SELECT * FROM station_trips_clean
""").df()

    line                      station  scheduled_trips
0      2                     BATHURST             2137
1      2                          BAY             2136
2      4                      BAYVIEW             1755
3      4                    BESSARION             1758
4      1                  BLOOR-YONGE             2196
5      2                    BROADVIEW             2133
6      2                 CASTLE FRANK             2133
7      1                    CEDARVALE             2181
8      2                      CHESTER             2133
9      2                     CHRISTIE             2139
10     1                      COLLEGE             2195
11     2                      COXWELL             2158
12     1                   DAVISVILLE             2190
13     4                    DON MILLS             1761
14     2                     DONLANDS             2133
15     1               DOWNSVIEW PARK             2154
16     2                     DUFFERIN             2139
17     2                  DUNDAS WEST             2139
18     1                       DUPONT             2184
19     1                     EGLINTON             2223
..   ...                          ...              ...
54     1                      SPADINA             2184
55     1                    ST ANDREW             2191
56     1                     ST CLAIR             2196
57     1                ST CLAIR WEST             2184
58     2                    ST GEORGE             2137
59     1                    ST GEORGE             2189
60     1                   ST PATRICK             2191
61     1                   SUMMERHILL             2196
62     1                          TMU             2195
63     1                        UNION             2195
64     1  VAUGHAN METROPOLITAN CENTRE             2154
65     2                VICTORIA PARK             2158
66     2                       WARDEN             2158
67     1                    WELLESLEY             2195
68     1                       WILSON             2181
69     2                     WOODBINE             2158
70     2                  BLOOR-YONGE             2136
71     1                   YORK MILLS             2224
72     1              YORK UNIVERSITY             2154
73     1                     YORKDALE             2181

[74 rows x 3 columns]

## Confidence intervals

Parametric bootstrap: 5,000 Poisson draws per station-line, 2.5th and 97.5th percentiles.

Limitation — delays cluster, so counts are overdispersed and these intervals are too narrow.

In [187]:
df_ci = con.sql("""
    SELECT t1.station, route, delays, scheduled_trips
    FROM station_unreliability_2018 t1 
    JOIN station_trips_clean t2 ON t1.station = t2.station AND t1.route = t2.Line
""").df()

import numpy as np
rng = np.random.default_rng(1)

sims = rng.poisson(df_ci['delays'].values,size=(5000, len(df_ci)))

rates = sims / df_ci['scheduled_trips'].values

df_ci['ci_low'], df_ci['ci_high'] = np.percentile(rates, [2.5, 97.5], axis=0)
df_ci['rate'] = df_ci['delays'] / df_ci['scheduled_trips']

baseline = df_ci['delays'].sum() / df_ci['scheduled_trips'].sum()
df_ci['worse_than_baseline'] = df_ci['ci_low'] > baseline

df_ci.sort_values('rate', ascending=False).head(15)

,station,route,delays,scheduled_trips,ci_low,ci_high,rate,worse_than_baseline
0,VAUGHAN METROPOLITAN CENTRE,1,3032,2154,1.360713,1.457289,1.407614,True
1,FINCH,1,2924,2224,1.268424,1.363759,1.314748,True
2,KENNEDY,2,2754,2158,1.230769,1.323448,1.276182,True
3,KIPLING,2,2488,2155,1.109965,1.200000,1.154524,True
4,EGLINTON,1,2462,2223,1.063878,1.151597,1.107512,True
5,WILSON,1,2225,2181,0.978450,1.063274,1.020174,True
6,BLOOR-YONGE,1,1928,2196,0.838342,0.917133,0.877960,True
7,SHEPPARD WEST,1,1584,2154,0.699164,0.772052,0.735376,True
9,COXWELL,2,1463,2158,0.642725,0.712697,0.677943,True
8,DAVISVILLE,1,1477,2190,0.639726,0.708219,0.674429,True
10,ST GEORGE,1,1345,2189,0.582458,0.647328,0.614436,True
12,BLOOR-YONGE,2,1249,2136,0.552434,0.617053,0.584738,True
11,WARDEN,2,1261,2158,0.552363,0.617702,0.584337,True
13,GREENWOOD,2,1219,2158,0.533364,0.597324,0.564875,True
14,ST CLAIR,1,1180,2196,0.507286,0.567851,0.537341,True

## Export

`station_data_final` — 2018 metrics, intervals and coordinates, one row per station-line.
`rank_comparison` — the same ranks in long format for a Tableau slope chart.

In [188]:
con.sql("""
    CREATE OR REPLACE TABLE station_ci AS
        SELECT * FROM df_ci
""")

con.sql("""
    CREATE OR REPLACE TABLE station_data_final AS
        SELECT * EXCLUDE(t2.station, t2.delays, rate, t2.route, t3.station, t3.line, t3.scheduled_trips) FROM station_unreliability_2018 t1 
        JOIN station_ci t2 
            ON t1.station = t2.station AND t1.route = t2.route
        LEFT JOIN station_geo t3 ON t1.station = t3.station AND t1.route = t3.line
""")

con.sql("""
    SELECT * FROM station_data_final
""").df()


con.sql("""
    COPY station_data_final TO 'output/station_final.csv' (HEADER, DELIMITER ',')
""")

In [189]:
con.sql("""
    SELECT * FROM station_data_final
""").df()

,station,delay_rate,delays,total_delay,avg_delay,p50,p95,route,adjusted_rank,raw_rank,delta,scheduled_trips,ci_low,ci_high,worse_than_baseline,lat,lon
0,VAUGHAN METROPOLITAN CENTRE,1.407614,3032,14140.0,4.663588,3.0,9.00,1,1,1,0,2154,1.360713,1.457289,True,43.794021,-79.527906
1,FINCH,1.314748,2924,15404.0,5.268126,4.0,11.00,1,2,2,0,2224,1.268424,1.363759,True,43.780503,-79.415488
2,KENNEDY,1.276182,2754,15916.0,5.779230,4.0,14.00,2,3,3,0,2158,1.230769,1.323448,True,43.732324,-79.264234
3,KIPLING,1.154524,2488,14643.0,5.885450,4.0,13.00,2,4,4,0,2155,1.109965,1.200000,True,43.637518,-79.535794
4,EGLINTON,1.107512,2462,16672.0,6.771730,5.0,15.00,1,5,5,0,2223,1.063878,1.151597,True,43.705615,-79.398636
5,WILSON,1.020174,2225,13220.0,5.941573,4.0,14.00,1,6,6,0,2181,0.978450,1.063274,True,43.734452,-79.450043
6,BLOOR-YONGE,0.877960,1928,12877.0,6.678942,4.0,17.00,1,7,7,0,2196,0.838342,0.917133,True,43.670546,-79.385654
7,SHEPPARD WEST,0.735376,1584,12838.0,8.104798,5.0,18.00,1,8,8,0,2154,0.699164,0.772052,True,43.749702,-79.462407
8,DAVISVILLE,0.674429,1477,10583.0,7.165200,5.0,17.00,1,10,9,-1,2190,0.639726,0.708219,True,43.697650,-79.397091
9,COXWELL,0.677943,1463,8417.0,5.753247,4.0,12.00,2,9,10,1,2158,0.642725,0.712697,True,43.684404,-79.322808
10,ST GEORGE,0.614436,1345,9432.0,7.012639,5.0,16.00,1,11,11,0,2189,0.582458,0.647328,True,43.668399,-79.398792
11,WARDEN,0.584337,1261,10599.0,8.405234,5.0,23.00,2,13,12,-1,2158,0.552363,0.617702,True,43.711569,-79.278930
12,BLOOR-YONGE,0.584738,1249,9780.0,7.830264,5.0,20.00,2,12,13,1,2136,0.552434,0.617053,True,43.671023,-79.386374
13,GREENWOOD,0.564875,1219,7569.0,6.209188,4.0,15.10,2,14,14,0,2158,0.533364,0.597324,True,43.682694,-79.330865
14,ST CLAIR,0.537341,1180,8507.0,7.209322,5.0,17.00,1,15,15,0,2196,0.507286,0.567851,True,43.688049,-79.393289
15,UNION,0.479727,1053,8264.0,7.848053,5.0,19.00,1,16,16,0,2195,0.451025,0.509339,True,43.645699,-79.380588
16,LAWRENCE,0.461538,1026,8748.0,8.526316,5.0,21.00,1,19,17,-2,2223,0.433648,0.489879,True,43.725959,-79.402392
17,ST CLAIR WEST,0.467949,1022,7748.0,7.581213,5.0,17.00,1,17,18,1,2184,0.439103,0.496337,True,43.684551,-79.415641
18,ROSEDALE,0.457650,1005,7817.0,7.778109,5.0,20.00,1,20,19,-1,2196,0.429417,0.486794,True,43.676649,-79.388339
19,KEELE,0.464037,1000,7839.0,7.839000,5.0,18.00,2,18,20,2,2155,0.435731,0.493735,True,43.655497,-79.459552
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54,DUFFERIN,0.228612,489,3985.0,8.149284,4.0,21.00,2,55,55,0,2139,0.208976,0.249649,False,43.660698,-79.434795
55,WOODBINE,0.226135,488,6051.0,12.399590,5.0,28.30,2,57,56,-1,2158,0.206673,0.246525,False,43.686504,-79.313108
56,FINCH WEST,0.226091,487,3538.0,7.264887,5.0,19.00,1,58,57,-1,2154,0.205664,0.246518,False,43.764855,-79.491118
57,ST ANDREW,0.221360,485,3694.0,7.616495,5.0,19.00,1,59,58,-1,2191,0.201734,0.241442,False,43.647650,-79.384789
58,CHESTER,0.226910,484,3268.0,6.752066,5.0,18.00,2,56,59,3,2133,0.207220,0.247070,False,43.678296,-79.352520
59,ROYAL YORK,0.220882,476,4395.0,9.233193,5.0,22.25,2,60,60,0,2155,0.201392,0.240835,False,43.648447,-79.509604
60,OSGOODE,0.216796,475,3599.0,7.576842,5.0,22.30,1,61,61,0,2191,0.197615,0.235965,False,43.651100,-79.386688
61,QUEEN'S PARK,0.213796,468,3198.0,6.833333,5.0,16.00,1,63,62,-1,2189,0.195055,0.232526,False,43.659901,-79.390490
62,OLD MILL,0.214385,462,4597.0,9.950216,5.0,23.00,2,62,63,1,2155,0.194896,0.234339,False,43.649752,-79.494151
63,GLENCAIRN,0.209995,458,4026.0,8.790393,5.0,20.00,1,64,64,0,2181,0.191197,0.229253,False,43.708602,-79.440544
64,JANE,0.196288,423,4272.0,10.099291,5.0,26.90,2,66,65,-1,2155,0.178190,0.214849,False,43.649946,-79.483753
65,DOWNSVIEW PARK,0.194522,419,2863.0,6.832936,5.0,19.00,1,67,66,-1,2154,0.175952,0.213556,False,43.753311,-79.478693
66,HIGH PARK,0.187007,403,3394.0,8.421836,5.0,23.80,2,68,67,-1,2155,0.168910,0.206032,False,43.653697,-79.467852
67,LANSDOWNE,0.179991,385,3271.0,8.496104,5.0,21.80,2,70,68,-2,2139,0.162225,0.197756,False,43.659280,-79.442467
68,LESLIE,0.197615,348,2574.0,7.396552,5.0,17.00,4,65,69,4,1761,0.177172,0.218626,False,43.771298,-79.365892
69,PIONEER VILLAGE,0.155525,335,2408.0,7.188060,5.0,17.30,1,71,70,-1,2154,0.139276,0.172702,False,43.776745,-79.509352
70,RUNNYMEDE,0.152204,328,2910.0,8.871951,5.0,21.65,2,72,71,-1,2155,0.136427,0.168910,False,43.651897,-79.475853
71,BAYVIEW,0.183476,322,2641.0,8.201863,5.0,22.95,4,69,72,3,1755,0.164103,0.203419,False,43.766912,-79.386717
72,YORK UNIVERSITY,0.126277,272,1802.0,6.625000,5.0,17.45,1,73,73,0,2154,0.111885,0.141133,False,43.774097,-79.499888
73,BESSARION,0.125711,221,1566.0,7.085973,5.0,16.00,4,74,74,0,1758,0.109784,0.142776,False,43.769249,-79.376329

In [190]:
con.sql("""
    SELECT * FROM station_data_final LIMIT 5
""").df()

,station,delay_rate,delays,total_delay,avg_delay,p50,p95,route,adjusted_rank,raw_rank,delta,scheduled_trips,ci_low,ci_high,worse_than_baseline,lat,lon
0,VAUGHAN METROPOLITAN CENTRE,1.407614,3032,14140.0,4.663588,3.0,9.0,1,1,1,0,2154,1.360713,1.457289,True,43.794021,-79.527906
1,FINCH,1.314748,2924,15404.0,5.268126,4.0,11.0,1,2,2,0,2224,1.268424,1.363759,True,43.780503,-79.415488
2,KENNEDY,1.276182,2754,15916.0,5.779230,4.0,14.0,2,3,3,0,2158,1.230769,1.323448,True,43.732324,-79.264234
3,KIPLING,1.154524,2488,14643.0,5.885450,4.0,13.0,2,4,4,0,2155,1.109965,1.200000,True,43.637518,-79.535794
4,EGLINTON,1.107512,2462,16672.0,6.771730,5.0,15.0,1,5,5,0,2223,1.063878,1.151597,True,43.705615,-79.398636

In [191]:
con.sql("""
    CREATE OR REPLACE TABLE rank_comparison AS
        SELECT 
            station, 
            raw_rank AS rank_value, 
            'raw' AS rank_type, 
            route, 
            lat, lon 
        FROM station_data_final 
        UNION ALL
        SELECT 
            station, 
            adjusted_rank AS rank_value,
            'adjusted' AS rank_type,
            route,
            lat,
            lon
        FROM station_data_final
""")

con.sql("""
    SELECT * FROM rank_comparison
""").df()

con.sql("""
    COPY rank_comparison TO 'output/rank_comparison.csv' (HEADER, DELIMITER ',')
""")

In [192]:
con.sql("""
    SELECT * FROM rank_comparison
""").df()

,station,rank_value,rank_type,route,lat,lon
0,VAUGHAN METROPOLITAN CENTRE,1,raw,1,43.794021,-79.527906
1,FINCH,2,raw,1,43.780503,-79.415488
2,KENNEDY,3,raw,2,43.732324,-79.264234
3,KIPLING,4,raw,2,43.637518,-79.535794
4,EGLINTON,5,raw,1,43.705615,-79.398636
5,WILSON,6,raw,1,43.734452,-79.450043
6,BLOOR-YONGE,7,raw,1,43.670546,-79.385654
7,SHEPPARD WEST,8,raw,1,43.749702,-79.462407
8,DAVISVILLE,9,raw,1,43.697650,-79.397091
9,COXWELL,10,raw,2,43.684404,-79.322808
10,ST GEORGE,11,raw,1,43.668399,-79.398792
11,WARDEN,12,raw,2,43.711569,-79.278930
12,BLOOR-YONGE,13,raw,2,43.671023,-79.386374
13,GREENWOOD,14,raw,2,43.682694,-79.330865
14,ST CLAIR,15,raw,1,43.688049,-79.393289
15,UNION,16,raw,1,43.645699,-79.380588
16,LAWRENCE,17,raw,1,43.725959,-79.402392
17,ST CLAIR WEST,18,raw,1,43.684551,-79.415641
18,ROSEDALE,19,raw,1,43.676649,-79.388339
19,KEELE,20,raw,2,43.655497,-79.459552
...,...,...,...,...,...,...
128,DUFFERIN,55,adjusted,2,43.660698,-79.434795
129,WOODBINE,57,adjusted,2,43.686504,-79.313108
130,FINCH WEST,58,adjusted,1,43.764855,-79.491118
131,ST ANDREW,59,adjusted,1,43.647650,-79.384789
132,CHESTER,56,adjusted,2,43.678296,-79.352520
133,ROYAL YORK,60,adjusted,2,43.648447,-79.509604
134,OSGOODE,61,adjusted,1,43.651100,-79.386688
135,QUEEN'S PARK,63,adjusted,1,43.659901,-79.390490
136,OLD MILL,62,adjusted,2,43.649752,-79.494151
137,GLENCAIRN,64,adjusted,1,43.708602,-79.440544
138,JANE,66,adjusted,2,43.649946,-79.483753
139,DOWNSVIEW PARK,67,adjusted,1,43.753311,-79.478693
140,HIGH PARK,68,adjusted,2,43.653697,-79.467852
141,LANSDOWNE,70,adjusted,2,43.659280,-79.442467
142,LESLIE,65,adjusted,4,43.771298,-79.365892
143,PIONEER VILLAGE,71,adjusted,1,43.776745,-79.509352
144,RUNNYMEDE,72,adjusted,2,43.651897,-79.475853
145,BAYVIEW,69,adjusted,4,43.766912,-79.386717
146,YORK UNIVERSITY,73,adjusted,1,43.774097,-79.499888
147,BESSARION,74,adjusted,4,43.769249,-79.376329